//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenB.Site.ServiceSATH {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSATH.IServiceSath")]
    public interface IServiceSath {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getDatosRUC", ReplyAction="http://tempuri.org/IServiceSath/getDatosRUCResponse")]
        OpenB.Entidad.ws.ERespuestaS getDatosRUC(string nroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getDatosRUC", ReplyAction="http://tempuri.org/IServiceSath/getDatosRUCResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getDatosRUCAsync(string nroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getDatosSecundarios", ReplyAction="http://tempuri.org/IServiceSath/getDatosSecundariosResponse")]
        OpenB.Entidad.ws.ERespuestaS getDatosSecundarios(string nroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getDatosSecundarios", ReplyAction="http://tempuri.org/IServiceSath/getDatosSecundariosResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getDatosSecundariosAsync(string nroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getDomicilioLegal", ReplyAction="http://tempuri.org/IServiceSath/getDomicilioLegalResponse")]
        OpenB.Entidad.ws.ERespuestaS getDomicilioLegal(string nroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getDomicilioLegal", ReplyAction="http://tempuri.org/IServiceSath/getDomicilioLegalResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getDomicilioLegalAsync(string nroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getRepresentanteLegal", ReplyAction="http://tempuri.org/IServiceSath/getRepresentanteLegalResponse")]
        OpenB.Entidad.ws.ERespuestaS getRepresentanteLegal(string nroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getRepresentanteLegal", ReplyAction="http://tempuri.org/IServiceSath/getRepresentanteLegalResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getRepresentanteLegalAsync(string nroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getDatosReniec", ReplyAction="http://tempuri.org/IServiceSath/getDatosReniecResponse")]
        OpenB.Entidad.ws.ERespuestaR getDatosReniec(string nroDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getDatosReniec", ReplyAction="http://tempuri.org/IServiceSath/getDatosReniecResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaR> getDatosReniecAsync(string nroDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getDatosSunedu", ReplyAction="http://tempuri.org/IServiceSath/getDatosSuneduResponse")]
        OpenB.Entidad.ws.EResGTSunedu getDatosSunedu(string nroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getDatosSunedu", ReplyAction="http://tempuri.org/IServiceSath/getDatosSuneduResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.EResGTSunedu> getDatosSuneduAsync(string nroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpNaveAeronave", ReplyAction="http://tempuri.org/IServiceSath/getSunarpNaveAeronaveResponse")]
        OpenB.Entidad.ws.ERespuestaS getSunarpNaveAeronave(string numeroMatricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpNaveAeronave", ReplyAction="http://tempuri.org/IServiceSath/getSunarpNaveAeronaveResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpNaveAeronaveAsync(string numeroMatricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpPJRazonSocial", ReplyAction="http://tempuri.org/IServiceSath/getSunarpPJRazonSocialResponse")]
        OpenB.Entidad.ws.ERespuestaS getSunarpPJRazonSocial(string razonSocial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpPJRazonSocial", ReplyAction="http://tempuri.org/IServiceSath/getSunarpPJRazonSocialResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpPJRazonSocialAsync(string razonSocial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpTitularidadPN", ReplyAction="http://tempuri.org/IServiceSath/getSunarpTitularidadPNResponse")]
        OpenB.Entidad.ws.ERespuestaS getSunarpTitularidadPN(string apellidoPaterno, string apellidoMaterno, string nombres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpTitularidadPN", ReplyAction="http://tempuri.org/IServiceSath/getSunarpTitularidadPNResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpTitularidadPNAsync(string apellidoPaterno, string apellidoMaterno, string nombres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpTitularidadPJ", ReplyAction="http://tempuri.org/IServiceSath/getSunarpTitularidadPJResponse")]
        OpenB.Entidad.ws.ERespuestaS getSunarpTitularidadPJ(string razonSocial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpTitularidadPJ", ReplyAction="http://tempuri.org/IServiceSath/getSunarpTitularidadPJResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpTitularidadPJAsync(string razonSocial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpTitularidadSIRSARP", ReplyAction="http://tempuri.org/IServiceSath/getSunarpTitularidadSIRSARPResponse")]
        OpenB.Entidad.ws.ERespuestaS getSunarpTitularidadSIRSARP(string apellidoPaterno, string apellidoMaterno, string nombres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpTitularidadSIRSARP", ReplyAction="http://tempuri.org/IServiceSath/getSunarpTitularidadSIRSARPResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpTitularidadSIRSARPAsync(string apellidoPaterno, string apellidoMaterno, string nombres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpTitularidadSIRSARPJ", ReplyAction="http://tempuri.org/IServiceSath/getSunarpTitularidadSIRSARPJResponse")]
        OpenB.Entidad.ws.ERespuestaS getSunarpTitularidadSIRSARPJ(string razonSocial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpTitularidadSIRSARPJ", ReplyAction="http://tempuri.org/IServiceSath/getSunarpTitularidadSIRSARPJResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpTitularidadSIRSARPJAsync(string razonSocial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpOficinas", ReplyAction="http://tempuri.org/IServiceSath/getSunarpOficinasResponse")]
        OpenB.Entidad.ws.ERespuestaS getSunarpOficinas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpOficinas", ReplyAction="http://tempuri.org/IServiceSath/getSunarpOficinasResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpOficinasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpListarAsientos", ReplyAction="http://tempuri.org/IServiceSath/getSunarpListarAsientosResponse")]
        OpenB.Entidad.ws.ERespuestaS getSunarpListarAsientos(string zona, string oficina, string partida, string registro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpListarAsientos", ReplyAction="http://tempuri.org/IServiceSath/getSunarpListarAsientosResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpListarAsientosAsync(string zona, string oficina, string partida, string registro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpListarAsientosSIRSARP", ReplyAction="http://tempuri.org/IServiceSath/getSunarpListarAsientosSIRSARPResponse")]
        OpenB.Entidad.ws.ERespuestaS getSunarpListarAsientosSIRSARP(string zona, string oficina, string partida, string registro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpListarAsientosSIRSARP", ReplyAction="http://tempuri.org/IServiceSath/getSunarpListarAsientosSIRSARPResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpListarAsientosSIRSARPAsync(string zona, string oficina, string partida, string registro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpVerDetalleRPV", ReplyAction="http://tempuri.org/IServiceSath/getSunarpVerDetalleRPVResponse")]
        OpenB.Entidad.ws.ERespuestaS getSunarpVerDetalleRPV(string zona, string oficina, string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpVerDetalleRPV", ReplyAction="http://tempuri.org/IServiceSath/getSunarpVerDetalleRPVResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpVerDetalleRPVAsync(string zona, string oficina, string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpVerDetalleRPVExtra", ReplyAction="http://tempuri.org/IServiceSath/getSunarpVerDetalleRPVExtraResponse")]
        OpenB.Entidad.ws.ERespuestaS getSunarpVerDetalleRPVExtra(string zona, string oficina, string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpVerDetalleRPVExtra", ReplyAction="http://tempuri.org/IServiceSath/getSunarpVerDetalleRPVExtraResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpVerDetalleRPVExtraAsync(string zona, string oficina, string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpVerAsientos", ReplyAction="http://tempuri.org/IServiceSath/getSunarpVerAsientosResponse")]
        OpenB.Entidad.ws.ERespuestaS getSunarpVerAsientos(string transaccion, string idImg, string tipo, string nroTotalPag, string nroPagRef, string pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpVerAsientos", ReplyAction="http://tempuri.org/IServiceSath/getSunarpVerAsientosResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpVerAsientosAsync(string transaccion, string idImg, string tipo, string nroTotalPag, string nroPagRef, string pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpVerAsientoSIRSARP", ReplyAction="http://tempuri.org/IServiceSath/getSunarpVerAsientoSIRSARPResponse")]
        OpenB.Entidad.ws.ERespuestaS getSunarpVerAsientoSIRSARP(string transaccion, string idImg, string tipo, string nroTotalPag, string nroPagRef, string pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getSunarpVerAsientoSIRSARP", ReplyAction="http://tempuri.org/IServiceSath/getSunarpVerAsientoSIRSARPResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpVerAsientoSIRSARPAsync(string transaccion, string idImg, string tipo, string nroTotalPag, string nroPagRef, string pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getMigracionesDocumento", ReplyAction="http://tempuri.org/IServiceSath/getMigracionesDocumentoResponse")]
        OpenB.Entidad.ws.ERespuestaM getMigracionesDocumento(string nroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getMigracionesDocumento", ReplyAction="http://tempuri.org/IServiceSath/getMigracionesDocumentoResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaM> getMigracionesDocumentoAsync(string nroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getAntJudiciales", ReplyAction="http://tempuri.org/IServiceSath/getAntJudicialesResponse")]
        OpenB.Entidad.ws.EResAntJudicial getAntJudiciales(string nroDocumento, string apePaterno, string apeMaterno, string Nombres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getAntJudiciales", ReplyAction="http://tempuri.org/IServiceSath/getAntJudicialesResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.EResAntJudicial> getAntJudicialesAsync(string nroDocumento, string apePaterno, string apeMaterno, string Nombres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getAntPenales", ReplyAction="http://tempuri.org/IServiceSath/getAntPenalesResponse")]
        OpenB.Entidad.ws.EResAntPenal getAntPenales(string nroDocumento, string apePaterno, string apeMaterno, string pNombres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getAntPenales", ReplyAction="http://tempuri.org/IServiceSath/getAntPenalesResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.EResAntPenal> getAntPenalesAsync(string nroDocumento, string apePaterno, string apeMaterno, string pNombres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getAntPoliciales", ReplyAction="http://tempuri.org/IServiceSath/getAntPolicialesResponse")]
        OpenB.Entidad.ws.EResAntPolicial getAntPoliciales(string nroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getAntPoliciales", ReplyAction="http://tempuri.org/IServiceSath/getAntPolicialesResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.EResAntPolicial> getAntPolicialesAsync(string nroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getMtcDatosLicencia", ReplyAction="http://tempuri.org/IServiceSath/getMtcDatosLicenciaResponse")]
        OpenB.Entidad.ws.ERespuestaS getMtcDatosLicencia(string iTipoDocumento, string sNumDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getMtcDatosLicencia", ReplyAction="http://tempuri.org/IServiceSath/getMtcDatosLicenciaResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getMtcDatosLicenciaAsync(string iTipoDocumento, string sNumDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getMtcRecordConductor", ReplyAction="http://tempuri.org/IServiceSath/getMtcRecordConductorResponse")]
        OpenB.Entidad.ws.ERespuestaS getMtcRecordConductor(string Tipo_Documento, string Numero_Documento, string Numero_Record);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getMtcRecordConductor", ReplyAction="http://tempuri.org/IServiceSath/getMtcRecordConductorResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getMtcRecordConductorAsync(string Tipo_Documento, string Numero_Documento, string Numero_Record);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getMtcDatosPapeletas", ReplyAction="http://tempuri.org/IServiceSath/getMtcDatosPapeletasResponse")]
        OpenB.Entidad.ws.ERespuestaS getMtcDatosPapeletas(string iTipoDocumento, string sNumDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getMtcDatosPapeletas", ReplyAction="http://tempuri.org/IServiceSath/getMtcDatosPapeletasResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getMtcDatosPapeletasAsync(string iTipoDocumento, string sNumDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getMtcUltimaLicencia", ReplyAction="http://tempuri.org/IServiceSath/getMtcUltimaLicenciaResponse")]
        OpenB.Entidad.ws.ERespuestaS getMtcUltimaLicencia(string iTipoDocumento, string sNumDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getMtcUltimaLicencia", ReplyAction="http://tempuri.org/IServiceSath/getMtcUltimaLicenciaResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getMtcUltimaLicenciaAsync(string iTipoDocumento, string sNumDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getMtcUltimasSanciones", ReplyAction="http://tempuri.org/IServiceSath/getMtcUltimasSancionesResponse")]
        OpenB.Entidad.ws.ERespuestaS getMtcUltimasSanciones(string iTipoDocumento, string sNumDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSath/getMtcUltimasSanciones", ReplyAction="http://tempuri.org/IServiceSath/getMtcUltimasSancionesResponse")]
        System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getMtcUltimasSancionesAsync(string iTipoDocumento, string sNumDocumento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSathChannel : OpenB.Site.ServiceSATH.IServiceSath, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSathClient : System.ServiceModel.ClientBase<OpenB.Site.ServiceSATH.IServiceSath>, OpenB.Site.ServiceSATH.IServiceSath {
        
        public ServiceSathClient() {
        }
        
        public ServiceSathClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSathClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSathClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSathClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OpenB.Entidad.ws.ERespuestaS getDatosRUC(string nroDocumento) {
            return base.Channel.getDatosRUC(nroDocumento);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getDatosRUCAsync(string nroDocumento) {
            return base.Channel.getDatosRUCAsync(nroDocumento);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getDatosSecundarios(string nroDocumento) {
            return base.Channel.getDatosSecundarios(nroDocumento);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getDatosSecundariosAsync(string nroDocumento) {
            return base.Channel.getDatosSecundariosAsync(nroDocumento);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getDomicilioLegal(string nroDocumento) {
            return base.Channel.getDomicilioLegal(nroDocumento);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getDomicilioLegalAsync(string nroDocumento) {
            return base.Channel.getDomicilioLegalAsync(nroDocumento);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getRepresentanteLegal(string nroDocumento) {
            return base.Channel.getRepresentanteLegal(nroDocumento);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getRepresentanteLegalAsync(string nroDocumento) {
            return base.Channel.getRepresentanteLegalAsync(nroDocumento);
        }
        
        public OpenB.Entidad.ws.ERespuestaR getDatosReniec(string nroDNI) {
            return base.Channel.getDatosReniec(nroDNI);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaR> getDatosReniecAsync(string nroDNI) {
            return base.Channel.getDatosReniecAsync(nroDNI);
        }
        
        public OpenB.Entidad.ws.EResGTSunedu getDatosSunedu(string nroDocumento) {
            return base.Channel.getDatosSunedu(nroDocumento);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.EResGTSunedu> getDatosSuneduAsync(string nroDocumento) {
            return base.Channel.getDatosSuneduAsync(nroDocumento);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getSunarpNaveAeronave(string numeroMatricula) {
            return base.Channel.getSunarpNaveAeronave(numeroMatricula);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpNaveAeronaveAsync(string numeroMatricula) {
            return base.Channel.getSunarpNaveAeronaveAsync(numeroMatricula);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getSunarpPJRazonSocial(string razonSocial) {
            return base.Channel.getSunarpPJRazonSocial(razonSocial);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpPJRazonSocialAsync(string razonSocial) {
            return base.Channel.getSunarpPJRazonSocialAsync(razonSocial);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getSunarpTitularidadPN(string apellidoPaterno, string apellidoMaterno, string nombres) {
            return base.Channel.getSunarpTitularidadPN(apellidoPaterno, apellidoMaterno, nombres);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpTitularidadPNAsync(string apellidoPaterno, string apellidoMaterno, string nombres) {
            return base.Channel.getSunarpTitularidadPNAsync(apellidoPaterno, apellidoMaterno, nombres);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getSunarpTitularidadPJ(string razonSocial) {
            return base.Channel.getSunarpTitularidadPJ(razonSocial);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpTitularidadPJAsync(string razonSocial) {
            return base.Channel.getSunarpTitularidadPJAsync(razonSocial);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getSunarpTitularidadSIRSARP(string apellidoPaterno, string apellidoMaterno, string nombres) {
            return base.Channel.getSunarpTitularidadSIRSARP(apellidoPaterno, apellidoMaterno, nombres);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpTitularidadSIRSARPAsync(string apellidoPaterno, string apellidoMaterno, string nombres) {
            return base.Channel.getSunarpTitularidadSIRSARPAsync(apellidoPaterno, apellidoMaterno, nombres);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getSunarpTitularidadSIRSARPJ(string razonSocial) {
            return base.Channel.getSunarpTitularidadSIRSARPJ(razonSocial);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpTitularidadSIRSARPJAsync(string razonSocial) {
            return base.Channel.getSunarpTitularidadSIRSARPJAsync(razonSocial);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getSunarpOficinas() {
            return base.Channel.getSunarpOficinas();
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpOficinasAsync() {
            return base.Channel.getSunarpOficinasAsync();
        }
        
        public OpenB.Entidad.ws.ERespuestaS getSunarpListarAsientos(string zona, string oficina, string partida, string registro) {
            return base.Channel.getSunarpListarAsientos(zona, oficina, partida, registro);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpListarAsientosAsync(string zona, string oficina, string partida, string registro) {
            return base.Channel.getSunarpListarAsientosAsync(zona, oficina, partida, registro);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getSunarpListarAsientosSIRSARP(string zona, string oficina, string partida, string registro) {
            return base.Channel.getSunarpListarAsientosSIRSARP(zona, oficina, partida, registro);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpListarAsientosSIRSARPAsync(string zona, string oficina, string partida, string registro) {
            return base.Channel.getSunarpListarAsientosSIRSARPAsync(zona, oficina, partida, registro);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getSunarpVerDetalleRPV(string zona, string oficina, string placa) {
            return base.Channel.getSunarpVerDetalleRPV(zona, oficina, placa);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpVerDetalleRPVAsync(string zona, string oficina, string placa) {
            return base.Channel.getSunarpVerDetalleRPVAsync(zona, oficina, placa);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getSunarpVerDetalleRPVExtra(string zona, string oficina, string placa) {
            return base.Channel.getSunarpVerDetalleRPVExtra(zona, oficina, placa);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpVerDetalleRPVExtraAsync(string zona, string oficina, string placa) {
            return base.Channel.getSunarpVerDetalleRPVExtraAsync(zona, oficina, placa);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getSunarpVerAsientos(string transaccion, string idImg, string tipo, string nroTotalPag, string nroPagRef, string pagina) {
            return base.Channel.getSunarpVerAsientos(transaccion, idImg, tipo, nroTotalPag, nroPagRef, pagina);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpVerAsientosAsync(string transaccion, string idImg, string tipo, string nroTotalPag, string nroPagRef, string pagina) {
            return base.Channel.getSunarpVerAsientosAsync(transaccion, idImg, tipo, nroTotalPag, nroPagRef, pagina);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getSunarpVerAsientoSIRSARP(string transaccion, string idImg, string tipo, string nroTotalPag, string nroPagRef, string pagina) {
            return base.Channel.getSunarpVerAsientoSIRSARP(transaccion, idImg, tipo, nroTotalPag, nroPagRef, pagina);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getSunarpVerAsientoSIRSARPAsync(string transaccion, string idImg, string tipo, string nroTotalPag, string nroPagRef, string pagina) {
            return base.Channel.getSunarpVerAsientoSIRSARPAsync(transaccion, idImg, tipo, nroTotalPag, nroPagRef, pagina);
        }
        
        public OpenB.Entidad.ws.ERespuestaM getMigracionesDocumento(string nroDocumento) {
            return base.Channel.getMigracionesDocumento(nroDocumento);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaM> getMigracionesDocumentoAsync(string nroDocumento) {
            return base.Channel.getMigracionesDocumentoAsync(nroDocumento);
        }
        
        public OpenB.Entidad.ws.EResAntJudicial getAntJudiciales(string nroDocumento, string apePaterno, string apeMaterno, string Nombres) {
            return base.Channel.getAntJudiciales(nroDocumento, apePaterno, apeMaterno, Nombres);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.EResAntJudicial> getAntJudicialesAsync(string nroDocumento, string apePaterno, string apeMaterno, string Nombres) {
            return base.Channel.getAntJudicialesAsync(nroDocumento, apePaterno, apeMaterno, Nombres);
        }
        
        public OpenB.Entidad.ws.EResAntPenal getAntPenales(string nroDocumento, string apePaterno, string apeMaterno, string pNombres) {
            return base.Channel.getAntPenales(nroDocumento, apePaterno, apeMaterno, pNombres);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.EResAntPenal> getAntPenalesAsync(string nroDocumento, string apePaterno, string apeMaterno, string pNombres) {
            return base.Channel.getAntPenalesAsync(nroDocumento, apePaterno, apeMaterno, pNombres);
        }
        
        public OpenB.Entidad.ws.EResAntPolicial getAntPoliciales(string nroDocumento) {
            return base.Channel.getAntPoliciales(nroDocumento);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.EResAntPolicial> getAntPolicialesAsync(string nroDocumento) {
            return base.Channel.getAntPolicialesAsync(nroDocumento);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getMtcDatosLicencia(string iTipoDocumento, string sNumDocumento) {
            return base.Channel.getMtcDatosLicencia(iTipoDocumento, sNumDocumento);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getMtcDatosLicenciaAsync(string iTipoDocumento, string sNumDocumento) {
            return base.Channel.getMtcDatosLicenciaAsync(iTipoDocumento, sNumDocumento);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getMtcRecordConductor(string Tipo_Documento, string Numero_Documento, string Numero_Record) {
            return base.Channel.getMtcRecordConductor(Tipo_Documento, Numero_Documento, Numero_Record);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getMtcRecordConductorAsync(string Tipo_Documento, string Numero_Documento, string Numero_Record) {
            return base.Channel.getMtcRecordConductorAsync(Tipo_Documento, Numero_Documento, Numero_Record);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getMtcDatosPapeletas(string iTipoDocumento, string sNumDocumento) {
            return base.Channel.getMtcDatosPapeletas(iTipoDocumento, sNumDocumento);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getMtcDatosPapeletasAsync(string iTipoDocumento, string sNumDocumento) {
            return base.Channel.getMtcDatosPapeletasAsync(iTipoDocumento, sNumDocumento);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getMtcUltimaLicencia(string iTipoDocumento, string sNumDocumento) {
            return base.Channel.getMtcUltimaLicencia(iTipoDocumento, sNumDocumento);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getMtcUltimaLicenciaAsync(string iTipoDocumento, string sNumDocumento) {
            return base.Channel.getMtcUltimaLicenciaAsync(iTipoDocumento, sNumDocumento);
        }
        
        public OpenB.Entidad.ws.ERespuestaS getMtcUltimasSanciones(string iTipoDocumento, string sNumDocumento) {
            return base.Channel.getMtcUltimasSanciones(iTipoDocumento, sNumDocumento);
        }
        
        public System.Threading.Tasks.Task<OpenB.Entidad.ws.ERespuestaS> getMtcUltimasSancionesAsync(string iTipoDocumento, string sNumDocumento) {
            return base.Channel.getMtcUltimasSancionesAsync(iTipoDocumento, sNumDocumento);
        }
    }
}
