//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8825
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="INPEAJudicialesSoap11Binding", Namespace="http://endpoint.wsantjudiciales.inpe.gob.pe")]
public partial class INPEAJudiciales : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback getAntecedenteJudicialOperationCompleted;
    
    /// <remarks/>
    public INPEAJudiciales() {
        this.Url = "https://ws3.pide.gob.pe/services/INPEAJudiciales.INPEAJudicialesHttpsSoap11Endpoi" +
            "nt";
    }
    
    /// <remarks/>
    public event getAntecedenteJudicialCompletedEventHandler getAntecedenteJudicialCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getAntecedenteJudicial", RequestNamespace="http://endpoint.wsantjudiciales.inpe.gob.pe", ResponseNamespace="http://endpoint.wsantjudiciales.inpe.gob.pe", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("getAntecedenteJudicialReturn")]
    public string getAntecedenteJudicial(string apepat, string apemat, string nombres) {
        object[] results = this.Invoke("getAntecedenteJudicial", new object[] {
                    apepat,
                    apemat,
                    nombres});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetAntecedenteJudicial(string apepat, string apemat, string nombres, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getAntecedenteJudicial", new object[] {
                    apepat,
                    apemat,
                    nombres}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetAntecedenteJudicial(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getAntecedenteJudicialAsync(string apepat, string apemat, string nombres) {
        this.getAntecedenteJudicialAsync(apepat, apemat, nombres, null);
    }
    
    /// <remarks/>
    public void getAntecedenteJudicialAsync(string apepat, string apemat, string nombres, object userState) {
        if ((this.getAntecedenteJudicialOperationCompleted == null)) {
            this.getAntecedenteJudicialOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAntecedenteJudicialOperationCompleted);
        }
        this.InvokeAsync("getAntecedenteJudicial", new object[] {
                    apepat,
                    apemat,
                    nombres}, this.getAntecedenteJudicialOperationCompleted, userState);
    }
    
    private void OngetAntecedenteJudicialOperationCompleted(object arg) {
        if ((this.getAntecedenteJudicialCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getAntecedenteJudicialCompleted(this, new getAntecedenteJudicialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void getAntecedenteJudicialCompletedEventHandler(object sender, getAntecedenteJudicialCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getAntecedenteJudicialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getAntecedenteJudicialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
