//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8825
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="PJAntecedentesPenalesSoap11Binding", Namespace="http://ws.verificacionAntecedentesPenalesWS.pj.gob.pe")]
public partial class PJAntecedentesPenales : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback verificarAntecedentesPenalesOperationCompleted;
    
    /// <remarks/>
    public PJAntecedentesPenales() {
        this.Url = "https://ws3.pide.gob.pe/services/PJAntecedentesPenales.PJAntecedentesPenalesHttpSo" +
            "ap11Endpoint";
    }
    
    /// <remarks/>
    public event verificarAntecedentesPenalesCompletedEventHandler verificarAntecedentesPenalesCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.verificacionAntecedentesPenalesWS.pj.gob.pe/NewOperation", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("verificarAntecedentesPenalesResponse", Namespace="http://ws.verificacionAntecedentesPenalesWS.pj.gob.pe")]
    public verificarAntecedentesPenalesResponse verificarAntecedentesPenales([System.Xml.Serialization.XmlElementAttribute("verificarAntecedentesPenales", Namespace="http://ws.verificacionAntecedentesPenalesWS.pj.gob.pe")] verificarAntecedentesPenales verificarAntecedentesPenales1) {
        object[] results = this.Invoke("verificarAntecedentesPenales", new object[] {
                    verificarAntecedentesPenales1});
        return ((verificarAntecedentesPenalesResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginverificarAntecedentesPenales(verificarAntecedentesPenales verificarAntecedentesPenales1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("verificarAntecedentesPenales", new object[] {
                    verificarAntecedentesPenales1}, callback, asyncState);
    }
    
    /// <remarks/>
    public verificarAntecedentesPenalesResponse EndverificarAntecedentesPenales(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((verificarAntecedentesPenalesResponse)(results[0]));
    }
    
    /// <remarks/>
    public void verificarAntecedentesPenalesAsync(verificarAntecedentesPenales verificarAntecedentesPenales1) {
        this.verificarAntecedentesPenalesAsync(verificarAntecedentesPenales1, null);
    }
    
    /// <remarks/>
    public void verificarAntecedentesPenalesAsync(verificarAntecedentesPenales verificarAntecedentesPenales1, object userState) {
        if ((this.verificarAntecedentesPenalesOperationCompleted == null)) {
            this.verificarAntecedentesPenalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverificarAntecedentesPenalesOperationCompleted);
        }
        this.InvokeAsync("verificarAntecedentesPenales", new object[] {
                    verificarAntecedentesPenales1}, this.verificarAntecedentesPenalesOperationCompleted, userState);
    }
    
    private void OnverificarAntecedentesPenalesOperationCompleted(object arg) {
        if ((this.verificarAntecedentesPenalesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.verificarAntecedentesPenalesCompleted(this, new verificarAntecedentesPenalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.verificacionAntecedentesPenalesWS.pj.gob.pe")]
public partial class verificarAntecedentesPenales {
    
    private string xApellidoPaternoField;
    
    private string xApellidoMaternoField;
    
    private string xNombre1Field;
    
    private string xNombre2Field;
    
    private string xNombre3Field;
    
    private string xDniField;
    
    private string xMotivoConsultaField;
    
    private string xProcesoEntidadConsultanteField;
    
    private string xRucEntidadConsultanteField;
    
    private string xIpPublicaField;
    
    private string xDniPersonaConsultanteField;
    
    private string xAudNombrePCField;
    
    private string xAudIPField;
    
    private string xAudNombreUsuarioField;
    
    private string xAudDireccionMACField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xApellidoPaterno {
        get {
            return this.xApellidoPaternoField;
        }
        set {
            this.xApellidoPaternoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xApellidoMaterno {
        get {
            return this.xApellidoMaternoField;
        }
        set {
            this.xApellidoMaternoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xNombre1 {
        get {
            return this.xNombre1Field;
        }
        set {
            this.xNombre1Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xNombre2 {
        get {
            return this.xNombre2Field;
        }
        set {
            this.xNombre2Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xNombre3 {
        get {
            return this.xNombre3Field;
        }
        set {
            this.xNombre3Field = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xDni {
        get {
            return this.xDniField;
        }
        set {
            this.xDniField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xMotivoConsulta {
        get {
            return this.xMotivoConsultaField;
        }
        set {
            this.xMotivoConsultaField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xProcesoEntidadConsultante {
        get {
            return this.xProcesoEntidadConsultanteField;
        }
        set {
            this.xProcesoEntidadConsultanteField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xRucEntidadConsultante {
        get {
            return this.xRucEntidadConsultanteField;
        }
        set {
            this.xRucEntidadConsultanteField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xIpPublica {
        get {
            return this.xIpPublicaField;
        }
        set {
            this.xIpPublicaField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xDniPersonaConsultante {
        get {
            return this.xDniPersonaConsultanteField;
        }
        set {
            this.xDniPersonaConsultanteField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xAudNombrePC {
        get {
            return this.xAudNombrePCField;
        }
        set {
            this.xAudNombrePCField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xAudIP {
        get {
            return this.xAudIPField;
        }
        set {
            this.xAudIPField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xAudNombreUsuario {
        get {
            return this.xAudNombreUsuarioField;
        }
        set {
            this.xAudNombreUsuarioField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xAudDireccionMAC {
        get {
            return this.xAudDireccionMACField;
        }
        set {
            this.xAudDireccionMACField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.verificacionAntecedentesPenalesWS.pj.gob.pe")]
public partial class verificarAntecedentesPenalesResponse {
    
    private string xCodigoRespuestaField;
    
    private string xMensajeRespuestaField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xCodigoRespuesta {
        get {
            return this.xCodigoRespuestaField;
        }
        set {
            this.xCodigoRespuestaField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string xMensajeRespuesta {
        get {
            return this.xMensajeRespuestaField;
        }
        set {
            this.xMensajeRespuestaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void verificarAntecedentesPenalesCompletedEventHandler(object sender, verificarAntecedentesPenalesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class verificarAntecedentesPenalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal verificarAntecedentesPenalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public verificarAntecedentesPenalesResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((verificarAntecedentesPenalesResponse)(this.results[0]));
        }
    }
}
