//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WSGradosBinding", Namespace="http://wsgt.sunedu.gob.pe/gradosws")]
public partial class WSGrados : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback opConsultarRNGTOperationCompleted;
    
    /// <remarks/>
    public WSGrados() {
        this.Url = "https://ws3.pide.gob.pe/services/SuneduGrados";
    }
    
    /// <remarks/>
    public event opConsultarRNGTCompletedEventHandler opConsultarRNGTCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://wsgt.sunedu.gob.pe/gradosws#opConsultarRNGT", RequestNamespace="http://wsgt.sunedu.gob.pe/gradosws", ResponseNamespace="http://wsgt.sunedu.gob.pe/gradosws")]
    [return: System.Xml.Serialization.SoapElementAttribute("respuesta")]
    public respuestaType opConsultarRNGT(usuarioType usuario, operacionType operacion, string nroDocIdentidad, out Object listaGTPersona) {
        object[] results = this.Invoke("opConsultarRNGT", new object[] {
                    usuario,
                    operacion,
                    nroDocIdentidad});
        listaGTPersona = ((Object)(results[1]));
        return ((respuestaType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginopConsultarRNGT(usuarioType usuario, operacionType operacion, string nroDocIdentidad, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("opConsultarRNGT", new object[] {
                    usuario,
                    operacion,
                    nroDocIdentidad}, callback, asyncState);
    }
    
    /// <remarks/>
    public respuestaType EndopConsultarRNGT(System.IAsyncResult asyncResult, out listaGTPersonaType listaGTPersona) {
        object[] results = this.EndInvoke(asyncResult);
        listaGTPersona = ((listaGTPersonaType)(results[1]));
        return ((respuestaType)(results[0]));
    }
    
    /// <remarks/>
    public void opConsultarRNGTAsync(usuarioType usuario, operacionType operacion, string nroDocIdentidad) {
        this.opConsultarRNGTAsync(usuario, operacion, nroDocIdentidad, null);
    }
    
    /// <remarks/>
    public void opConsultarRNGTAsync(usuarioType usuario, operacionType operacion, string nroDocIdentidad, object userState) {
        if ((this.opConsultarRNGTOperationCompleted == null)) {
            this.opConsultarRNGTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnopConsultarRNGTOperationCompleted);
        }
        this.InvokeAsync("opConsultarRNGT", new object[] {
                    usuario,
                    operacion,
                    nroDocIdentidad}, this.opConsultarRNGTOperationCompleted, userState);
    }
    
    private void OnopConsultarRNGTOperationCompleted(object arg) {
        if ((this.opConsultarRNGTCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.opConsultarRNGTCompleted(this, new opConsultarRNGTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://wsgt.sunedu.gob.pe/gradosws")]
public partial class usuarioType {
    
    private string usuarioField;
    
    private string claveField;
    
    private string idEntidadField;
    
    /// <remarks/>
    public string usuario {
        get {
            return this.usuarioField;
        }
        set {
            this.usuarioField = value;
        }
    }
    
    /// <remarks/>
    public string clave {
        get {
            return this.claveField;
        }
        set {
            this.claveField = value;
        }
    }
    
    /// <remarks/>
    public string idEntidad {
        get {
            return this.idEntidadField;
        }
        set {
            this.idEntidadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://wsgt.sunedu.gob.pe/gradosws")]
public partial class gtPersonaType {
    
    private string tipoDocumentoField;
    
    private string nroDocumentoField;
    
    private string apellidoPaternoField;
    
    private string apellidoMaternoField;
    
    private string nombresField;
    
    private string abreviaturaTituloField;
    
    private string tituloProfesionalField;
    
    private string universidadField;
    
    private string especialidadField;
    
    private string paisField;
    
    private string tipoInstitucionField;
    
    private string tipoGestionField;
    
    private string fechaEmisionField;
    
    private string resolucionField;
    
    private string fechaResolucionField;
    
    private string tipoGraduacionField;
    
    private string fechaGraduacionField;
    
    private string numeroDiplomaField;
    
    private string numeroLibroField;
    
    private string numeroFolioField;
    
    private string numeroRegistroField;
    
    private string nombreFacultadField;
    
    private string nombreCarreraField;
    
    private string nombreEscuelaField;
    
    private string cargoAutoridad1Field;
    
    private string nombreAutoridad1Field;
    
    private string cargoAutoridad2Field;
    
    private string nombreAutoridad2Field;
    
    private string cargoAutoridad3Field;
    
    private string nombreAutoridad3Field;
    
    private string numeroOficioField;
    
    private string flgResolucionNulidadField;
    
    private string nroResolucionNulidadField;
    
    private string fechaResolucionNulidadField;
    
    /// <remarks/>
    public string tipoDocumento {
        get {
            return this.tipoDocumentoField;
        }
        set {
            this.tipoDocumentoField = value;
        }
    }
    
    /// <remarks/>
    public string nroDocumento {
        get {
            return this.nroDocumentoField;
        }
        set {
            this.nroDocumentoField = value;
        }
    }
    
    /// <remarks/>
    public string apellidoPaterno {
        get {
            return this.apellidoPaternoField;
        }
        set {
            this.apellidoPaternoField = value;
        }
    }
    
    /// <remarks/>
    public string apellidoMaterno {
        get {
            return this.apellidoMaternoField;
        }
        set {
            this.apellidoMaternoField = value;
        }
    }
    
    /// <remarks/>
    public string nombres {
        get {
            return this.nombresField;
        }
        set {
            this.nombresField = value;
        }
    }
    
    /// <remarks/>
    public string abreviaturaTitulo {
        get {
            return this.abreviaturaTituloField;
        }
        set {
            this.abreviaturaTituloField = value;
        }
    }
    
    /// <remarks/>
    public string tituloProfesional {
        get {
            return this.tituloProfesionalField;
        }
        set {
            this.tituloProfesionalField = value;
        }
    }
    
    /// <remarks/>
    public string universidad {
        get {
            return this.universidadField;
        }
        set {
            this.universidadField = value;
        }
    }
    
    /// <remarks/>
    public string especialidad {
        get {
            return this.especialidadField;
        }
        set {
            this.especialidadField = value;
        }
    }
    
    /// <remarks/>
    public string pais {
        get {
            return this.paisField;
        }
        set {
            this.paisField = value;
        }
    }
    
    /// <remarks/>
    public string tipoInstitucion {
        get {
            return this.tipoInstitucionField;
        }
        set {
            this.tipoInstitucionField = value;
        }
    }
    
    /// <remarks/>
    public string tipoGestion {
        get {
            return this.tipoGestionField;
        }
        set {
            this.tipoGestionField = value;
        }
    }
    
    /// <remarks/>
    public string fechaEmision {
        get {
            return this.fechaEmisionField;
        }
        set {
            this.fechaEmisionField = value;
        }
    }
    
    /// <remarks/>
    public string resolucion {
        get {
            return this.resolucionField;
        }
        set {
            this.resolucionField = value;
        }
    }
    
    /// <remarks/>
    public string fechaResolucion {
        get {
            return this.fechaResolucionField;
        }
        set {
            this.fechaResolucionField = value;
        }
    }
    
    /// <remarks/>
    public string tipoGraduacion {
        get {
            return this.tipoGraduacionField;
        }
        set {
            this.tipoGraduacionField = value;
        }
    }
    
    /// <remarks/>
    public string fechaGraduacion {
        get {
            return this.fechaGraduacionField;
        }
        set {
            this.fechaGraduacionField = value;
        }
    }
    
    /// <remarks/>
    public string numeroDiploma {
        get {
            return this.numeroDiplomaField;
        }
        set {
            this.numeroDiplomaField = value;
        }
    }
    
    /// <remarks/>
    public string numeroLibro {
        get {
            return this.numeroLibroField;
        }
        set {
            this.numeroLibroField = value;
        }
    }
    
    /// <remarks/>
    public string numeroFolio {
        get {
            return this.numeroFolioField;
        }
        set {
            this.numeroFolioField = value;
        }
    }
    
    /// <remarks/>
    public string numeroRegistro {
        get {
            return this.numeroRegistroField;
        }
        set {
            this.numeroRegistroField = value;
        }
    }
    
    /// <remarks/>
    public string nombreFacultad {
        get {
            return this.nombreFacultadField;
        }
        set {
            this.nombreFacultadField = value;
        }
    }
    
    /// <remarks/>
    public string nombreCarrera {
        get {
            return this.nombreCarreraField;
        }
        set {
            this.nombreCarreraField = value;
        }
    }
    
    /// <remarks/>
    public string nombreEscuela {
        get {
            return this.nombreEscuelaField;
        }
        set {
            this.nombreEscuelaField = value;
        }
    }
    
    /// <remarks/>
    public string cargoAutoridad1 {
        get {
            return this.cargoAutoridad1Field;
        }
        set {
            this.cargoAutoridad1Field = value;
        }
    }
    
    /// <remarks/>
    public string nombreAutoridad1 {
        get {
            return this.nombreAutoridad1Field;
        }
        set {
            this.nombreAutoridad1Field = value;
        }
    }
    
    /// <remarks/>
    public string cargoAutoridad2 {
        get {
            return this.cargoAutoridad2Field;
        }
        set {
            this.cargoAutoridad2Field = value;
        }
    }
    
    /// <remarks/>
    public string nombreAutoridad2 {
        get {
            return this.nombreAutoridad2Field;
        }
        set {
            this.nombreAutoridad2Field = value;
        }
    }
    
    /// <remarks/>
    public string cargoAutoridad3 {
        get {
            return this.cargoAutoridad3Field;
        }
        set {
            this.cargoAutoridad3Field = value;
        }
    }
    
    /// <remarks/>
    public string nombreAutoridad3 {
        get {
            return this.nombreAutoridad3Field;
        }
        set {
            this.nombreAutoridad3Field = value;
        }
    }
    
    /// <remarks/>
    public string numeroOficio {
        get {
            return this.numeroOficioField;
        }
        set {
            this.numeroOficioField = value;
        }
    }
    
    /// <remarks/>
    public string flgResolucionNulidad {
        get {
            return this.flgResolucionNulidadField;
        }
        set {
            this.flgResolucionNulidadField = value;
        }
    }
    
    /// <remarks/>
    public string nroResolucionNulidad {
        get {
            return this.nroResolucionNulidadField;
        }
        set {
            this.nroResolucionNulidadField = value;
        }
    }
    
    /// <remarks/>
    public string fechaResolucionNulidad {
        get {
            return this.fechaResolucionNulidadField;
        }
        set {
            this.fechaResolucionNulidadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://wsgt.sunedu.gob.pe/gradosws")]
public partial class listaGTPersonaType {
    
    private gtPersonaType[] gtPersonaField;
    
    /// <remarks/>
    public gtPersonaType[] gtPersona {
        get {
            return this.gtPersonaField;
        }
        set {
            this.gtPersonaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://wsgt.sunedu.gob.pe/gradosws")]
public partial class respuestaType {
    
    private string fechaSuneduField;
    
    private string horaSuneduField;
    
    private string cGenericoField;
    
    private string dGenericaField;
    
    /// <remarks/>
    public string fechaSunedu {
        get {
            return this.fechaSuneduField;
        }
        set {
            this.fechaSuneduField = value;
        }
    }
    
    /// <remarks/>
    public string horaSunedu {
        get {
            return this.horaSuneduField;
        }
        set {
            this.horaSuneduField = value;
        }
    }
    
    /// <remarks/>
    public string cGenerico {
        get {
            return this.cGenericoField;
        }
        set {
            this.cGenericoField = value;
        }
    }
    
    /// <remarks/>
    public string dGenerica {
        get {
            return this.dGenericaField;
        }
        set {
            this.dGenericaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://wsgt.sunedu.gob.pe/gradosws")]
public partial class operacionType {
    
    private string fechaField;
    
    private string horaField;
    
    private string mac_wsServerField;
    
    private string ip_wsServerField;
    
    private string ip_wsUserField;
    
    /// <remarks/>
    public string fecha {
        get {
            return this.fechaField;
        }
        set {
            this.fechaField = value;
        }
    }
    
    /// <remarks/>
    public string hora {
        get {
            return this.horaField;
        }
        set {
            this.horaField = value;
        }
    }
    
    /// <remarks/>
    public string mac_wsServer {
        get {
            return this.mac_wsServerField;
        }
        set {
            this.mac_wsServerField = value;
        }
    }
    
    /// <remarks/>
    public string ip_wsServer {
        get {
            return this.ip_wsServerField;
        }
        set {
            this.ip_wsServerField = value;
        }
    }
    
    /// <remarks/>
    public string ip_wsUser {
        get {
            return this.ip_wsUserField;
        }
        set {
            this.ip_wsUserField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void opConsultarRNGTCompletedEventHandler(object sender, opConsultarRNGTCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class opConsultarRNGTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal opConsultarRNGTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public respuestaType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((respuestaType)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public listaGTPersonaType listaGTPersona {
        get {
            this.RaiseExceptionIfNecessary();
            return ((listaGTPersonaType)(this.results[1]));
        }
    }
}
